### ISSUE TITLE
New Setup: Everything's all cold and empty...

### ISSUE THREAD

**Issue by logan-wrld** [noryev/Leto#4]
![leto-config](https://user-images.githubusercontent.com/30084404/202595167-ca429ae1-fc3a-46fb-a7fb-ef5ac75c8f18.png)

**Comment by logan-wrld** [comment]
![fenringLietLogo](https://user-images.githubusercontent.com/30084404/201593300-a83b4463-78ab-4c91-b1d7-c952b95f38b1.png)
Here is a rough draft of the new project logo. Cleaning up with Illustrator then I will update with the better image when completed.

**Comment by logan-wrld** [comment]
![LetoLogo1](https://user-images.githubusercontent.com/30084404/201788326-b41d1ec4-e07d-4e7f-bd1f-f5b0ea9ae085.png)

**Comment by logan-wrld** [comment]
Method for combatting cross-origin scripting attacks. Using HTTP response headers to control what the user is allowed to load. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by logan-wrld** [comment]
![Group 18](https://user-images.githubusercontent.com/30084404/202093092-45701a02-398d-41e5-aaf1-e0edc34d9ccb.png)

**Comment by logan-wrld** [comment]
![LetoSpec](https://user-images.githubusercontent.com/30084404/202567863-ed3e8b02-9bb5-46bc-b8d5-7cdef5c92729.png)

**Comment by logan-wrld** [comment]
Now that everythings in the repo, get it running in Cloudflare

**Comment by noryev** [comment]
![leto-config](https://user-images.githubusercontent.com/30084404/202595099-a11854f2-7800-40d9-bf65-6d61b2d4f53f.png)
