### ISSUE TITLE
Fix endpoint

### ISSUE THREAD

**Issue by logan-wrld** [noryev/Leto#8]
dnsand s3 buckets configured, now take care of the API on Cloudflare

**Comment by logan-wrld** [comment]
API on Cloudflare responding- Move API over to lambda- add screenshot displaying responses

**Comment by logan-wrld** [comment]
Re-did the API in the current s3 bucket @ leto.gg @galaxyxtwo

**Comment by logan-wrld** [comment]
> Re-did the API in the current s3 bucket @ leto.gg @galaxyxtwo

@galaxyxtwo

**Comment by logan-wrld** [comment]
Added sentry logging to Cloudflare account with the "pinpoint problems" checklist
<img width="432" alt="Screenshot 2023-01-16 at 8 16 32 PM" src="https://user-images.githubusercontent.com/30084404/212795189-21f9695b-3ce6-4a30-94b1-fc4590755c5b.png">

**Comment by logan-wrld** [comment]
Contact gateway via "gateway.leto.gg" @galaxyxtwo- try on your browser- report what you find pls

**Comment by galaxyxtwo** [comment]
gateway.leto.gg works! It redirects to http://gateway.leto.gg.ipns.localhost:8080/. One thing I noticed, if you type Leto.gg in the browser, it is currently redirecting to https://s3.amazonaws.com/leto.gg/index.html.
